# Configuration for Groq Chat Interface
textsplitter:  
  chunk_size : 1024
  chunk_overlap : 200
  separators : ["\n", "\n\n"]


model:
  model_name: "mixtral-8x7b-32768" 
  temperature : 0.3


embeddings : 
  model_name : "model/bge-large-en-v1.5"
  model_kwargs : {"device": "cpu"}
  encode_kwargs : {"normalize_embeddings": True}